#ifndef CPCLICKABLELABEL_GLOBAL_H
#define CPCLICKABLELABEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPCLICKABLELABEL_LIBRARY)
#  define CPCLICKABLELABEL_EXPORT Q_DECL_EXPORT
#else
#  define CPCLICKABLELABEL_EXPORT Q_DECL_IMPORT
#endif

#endif // CPCLICKABLELABEL_GLOBAL_H
